version: '3.9'
services:
    api:
        build: ./api/
        ports:
            - '5000:5000'
        depends_on:
            - db
            - redis
        command: npm run dockerStart

    frontend:
        build: ./frontend/
        ports:
            - '3000:3000'
        depends_on:
            - api
        command: npm run dockerStart

    db:
        expose:
            - '27017'
        image: mongo:4.2.13-bionic

    redis:
        expose:
            - '6379'
        image: redis:6.2.2-alpine3.13
