version: '3.9'
services:
    api:
        build: ./api/
        ports:
            - '5000:5000'
        command: npm start

    frontend:
        build: ./frontend/
        ports:
            - '3000:3000'
        depends_on:
            - api
        command: npm run dockerStart
